## Chapter 3

In [1]:
import numpy as np
import pandas as pd

In [8]:
# Import .csv and create df
df = pd.read_csv('Chapter Exercise Data.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderID           1000 non-null   int64
 1   PricePerItem      1000 non-null   int64
 2   Quantity          1000 non-null   int64
 3   ShippingDistance  994 non-null    float64
 4   CustomerID        1000 non-null   int64
dtypes: float64(1), int64(4)
memory usage: 39.2 KB

In [ ]:
# Import .csv and create df
df = pd.read_csv('Chapter Exercise Data.csv')

In [10]:
# Import .csv and create df
df = pd.read_csv('Chapter Exercise Data.csv')
# Fill na values with zeros in df
df = df.fillna(0)
df.head()

   OrderID  PricePerItem  Quantity  ShippingDistance  CustomerID
0        1            10         5               3.0        6671
1        2            10        10              84.0        8647
2        3            10         1               0.0        4075
3        4            10        10              92.0        8452
4        5            10         3               2.0        2621

1. John realized that he wanted to add the amount he would make per order onto his DataFrame. Create a new column that displays the amount he would make per order.

In [11]:
df['Amount'] = df['PricePerItem']*df['Quantity']
df.head()

   OrderID  PricePerItem  Quantity  ShippingDistance  CustomerID  Amount
0        1            10         5               3.0        6671      50
1        2            10        10              84.0        8647     100
2        3            10         1               0.0        4075      10
3        4            10        10              92.0        8452     100
4        5            10         3               2.0        2621      30

2. John wants to send out thank you cards to the customers that spent at least $50 on their order. Filter the DataFrame for the list of customer IDs that fit this criteria.

In [18]:
df_50 = df[df['Amount'] >= 50]
df_50

     OrderID  PricePerItem  Quantity  ShippingDistance  CustomerID  Amount
0          1            10         5               3.0        6671      50
1          2            10        10              84.0        8647     100
3          4            10        10              92.0        8452     100
5          6            10         5               0.0        9160      50
7          8            10         8              65.0         809      80
..       ...           ...       ...               ...         ...     ...
993      994            10        10              75.0        1782     100
994      995            10         8              69.0        6587      80
995      996            10         8               2.0        6691      80
996      997            10         9              43.0        9782      90
998      999            10         9              49.0        5319      90

[600 rows x 6 columns]

In [24]:
df_50['CustomerID'].count()

np.int64(600)

3. John wants to send out a gift card for every 300th customer. Find the list of CustomerIDs that qualify for a gift card.

In [19]:
df.iloc[[299,599,899],4]

299     198
599    7682
899    1549
Name: CustomerID, dtype: int64

4. Find the average distance that a product travels when shipped.

In [20]:
df['ShippingDistance'].mean()

np.float64(48.541)

5. John recently hired a courier that delivers all his orders for a flat fee, so he no longer needs to know the shipping distance. Drop the shipping distance column.

In [23]:
df2=df.drop('ShippingDistance', axis=1)
df2

     OrderID  PricePerItem  Quantity  CustomerID  Amount
0          1            10         5        6671      50
1          2            10        10        8647     100
2          3            10         1        4075      10
3          4            10        10        8452     100
4          5            10         3        2621      30
..       ...           ...       ...         ...     ...
995      996            10         8        6691      80
996      997            10         9        9782      90
997      998            10         2        1096      20
998      999            10         9        5319      90
999     1000            10         4        8187      40

[1000 rows x 5 columns]

6. John wants to know from his orders what is the most popular order quantity amount. Find the count of each order quantity.

In [25]:
df['Quantity'].mode()

0    1
Name: Quantity, dtype: int64

In [26]:
Count_of_Quantity = df.groupby('Quantity')['OrderID'].count()
Count_of_Quantity

Quantity
1     113
2      95
3      98
4      94
5      98
6      91
7     103
8     102
9      96
10    110
Name: OrderID, dtype: int64